font_family      JetBrainsMono Nerd Font
font_size        11.0

background_opacity          0.60
dynamic_background_opacity  yes
window_padding_width  10
confirm_os_window_close 0

# Colores: generados por matugen (Material You desde wallpaper)
include matugen.conf
